- name: Install apps with homebrew
  homebrew: name={{ item }} state=present
  with_items:
    - go
    - nvm
    - git
    - redis
    - rabbitmq
    - helm
    - eksctl
    - circleci
    - k9s
    - jq
    - minikube
    - terraform
    - postgresql
    - zsh
    - wget
    - kubernetes-cli
    - awscli
    - libtool
    - autoconf
    - automake

- name: Install cask packages 
  homebrew_cask: name={{ item }} state=present
  with_items:
    - rectangle
    - microsoft-edge
    - microsoft-office
    - vscodium
    - slack
    - zoom
    - bitwarden
    - lens
    - github
    - obsidian
    - notion
    - tableplus
    - postman

